version: '3'
services:
  redis-server:
    image: 'redis'
    expose:
      - 6379
  node-app:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    ports:
      - '4002:5000'
    volumes:
      - /app/node_modules
      - /app/coverage
      - ./:/app
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
      - NODE_ENV=development
      - PORT=5000
      - ELASTICACHE_ENDPOINT=redis-server
      - ELASTICACHE_PORT=6379
    expose:
      - 5000
