AWSTemplateFormatVersion: '2010-09-09'
Description: This template create a redis cluster.
Parameters:
  EnvironmentName:
    Type: String
    Default: Demo1
    Description: Name of the environment.
  ClusterNodeType:
    Description: The compute and memory capacity of the nodes in the Redis Cluster
    Type: String
    Default: cache.t2.micro
    AllowedValues:
      - cache.t2.micro
      - cache.t2.small
  ElastiCachePort:
    Type: String
    Default: '6379'
    Description: Post for your Amazon ElastiCache instance

Resources:
  RedisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable Redis access
      VpcId:
        Fn::ImportValue: !Join [':', [!Ref EnvironmentName, 'VPCId']]
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          SourceSecurityGroupId:
            Fn::ImportValue: !Join [':', [!Ref 'EnvironmentName', 'FargateContainerSecurityGroup']]
        # - IpProtocol: tcp
        #   FromPort: 6379
        #   ToPort: 6379
        #   SourceSecurityGroupId: !Ref LambdaSecurityGroup
  RedisSubnetGroup:
    Type: 'AWS::ElastiCache::SubnetGroup'
    Properties:
      Description: The Subnet Group for the redis cluster
      SubnetIds:
        - Fn::ImportValue: !Join [':', [!Ref EnvironmentName, 'PrivateSubnetOne']]
        - Fn::ImportValue: !Join [':', [!Ref EnvironmentName, 'PrivateSubnetTwo']]

  RedisCluster:
    Type: 'AWS::ElastiCache::CacheCluster'
    Properties:
      AutoMinorVersionUpgrade: true
      # CacheNodeType: cache.t2.micro
      CacheNodeType: !Ref ClusterNodeType
      CacheSubnetGroupName: !Ref RedisSubnetGroup
      Engine: redis
      NumCacheNodes: 1
      Port: !Ref ElastiCachePort
      VpcSecurityGroupIds:
        - !Ref RedisSecurityGroup

Outputs:
  RedisHost:
    Description: Elastic Cache endpoint -  host url
    Value: !GetAtt RedisCluster.RedisEndpoint.Address
    Export:
      Name: !Join [':', [!Ref 'EnvironmentName', 'RedisHost']]
  RedisPort:
    Description: Elastic Cache endpoint -  host url
    Value: !GetAtt RedisCluster.RedisEndpoint.Port
    Export:
      Name: !Join [':', [!Ref 'EnvironmentName', 'RedisPort']]
