Description: >


  This template create vpc, nat, load-balancer, ecs cluster and deploy services.

  Author: Gulmohar<gulmoharsontakke@gmail.com>

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://msdemo-ecs-refarch.s3.us-east-2.amazonaws.com/cloudformation/01_vpc-network.yml
      Parameters:
        EnvironmentName: msdemo
  NAT:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://msdemo-ecs-refarch.s3.us-east-2.amazonaws.com/cloudformation/02_nat-gateway.yml
      Parameters:
        EnvironmentName: msdemo
  ALB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://msdemo-ecs-refarch.s3.us-east-2.amazonaws.com/cloudformation/03_load-balancer.yml
      Parameters:
        EnvironmentName: msdemo
  ECS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://msdemo-ecs-refarch.s3.us-east-2.amazonaws.com/cloudformation/04_ecs-cluster.yml
      Parameters:
        EnvironmentName: msdemo
  OrderService:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://msdemo-ecs-refarch.s3.us-east-2.amazonaws.com/cloudformation/05_customer-service.yml
      Parameters:
        EnvironmentName: msdemo
  CustomerService:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://msdemo-ecs-refarch.s3.us-east-2.amazonaws.com/cloudformation/06_order-service.yml
      Parameters:
        EnvironmentName: msdemo

Outputs:
  LoadBalancerUrl:
    Description: Load balancer url
    Value: !GetAtt ALB.Outputs.ExternalUrl
